### ISSUE TITLE
[Gallery] Zusätzliche Ansicht für Indexseite

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ACP3/cms#20]
```
Es sollte eine weitere Ansicht für die Auflistung der Fotogalerien geben, bei 
der das erste Bild bzw. ein benutzerdefiniertes Titelbild angezeigt wird.
```

Original issue reported on code.google.com by `tino.gor...@hotmail.com` on 16 Feb 2012 at 5:17

**Comment by tinogo** [comment]
This has been implemented with commit 80bb23be5a035c31b7590430fa6aab14d48d495f.
Therefore: Done! :)
