### ISSUE TITLE
Using internal data files of giggsey/Locale

### ISSUE THREAD

**Issue by giggsey** [ACP3/cms#57]
Hi,

I just noticed that you are using [giggsey/Locale](https://github.com/giggsey/Locale) in your project, and that you are requiring one of the data files directly from your code: [CountryList.php](https://github.com/ACP3/cms/blob/a20b00c64b330105db8f4e2d47ed1f5e7fdd873f/ACP3/Core/I18n/CountryList.php#L45)

When building the project, I did not intend for these files to be used directly, so I'm going to mark them as `@internal`. I'm going to maintain backwards compatibility for these files and their location until version 2.

To better aid your project, I'm happy to add some methods to the Locale class, so you can access the data properly.

If I add functions to get a list of supported locales, and all the country mappings for a particular locale, will these provide the needed functionality?

**Comment by tinogo** [comment]
Hi @giggsey,

sorry for the late reply.
Yes, this would be great, so I wouldn't have to rely on the internal structure of your project. :)

**Comment by giggsey** [comment]
@tinogo No worries. Would those two individual functions be all that you need?

**Comment by tinogo** [comment]
@giggsey Yes, that's all that I currently need. :)
The per locale script writing direction is handled separately by the library [fisharebest/localization](https://github.com/fisharebest/localization)

**Comment by giggsey** [comment]
[1.3](https://github.com/giggsey/Locale/releases/tag/1.3) has now been released. That should provide the functionality required.

**Comment by tinogo** [comment]
@giggsey Thanks! I've updated my code. :)
